shopt -s extglob
source $LOST_BUILDMK_ROOT/config.sh

echo "LD   $1/modules/ata"
$LOST_TOOLS_LD -oata.mod -Ttext=0x40000000 *.o --start-group $2 --end-group
$LOST_TOOLS_STRIP -s ata.mod -o $1/modules/ata
